# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_adult": "00_logisitc.ipynb"}

modules = ["io.py"]

doc_url = "https://spiaz.github.io/knowledge_distillation/"

git_url = "https://github.com/spiaz/knowledge_distillation/tree/main/"

def custom_doc_links(name): return None
