# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_ensemble.ipynb (unless otherwise specified).

__all__ = ['UnbiasedAverage']

# Cell
from sklearn.base import BaseEstimator, ClassifierMixin
import numpy as np

# Cell
class UnbiasedAverage(BaseEstimator, ClassifierMixin):
    """ Calculate the unbiased average of the input features"""

    def fit(self, X, y):
        pass

    def predict_proba(self, X):
        return np.mean(X, axis=1)

    def predict(self, X):
        return (self.predict_proba(X) >= .5).astype(int)
