# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_logisitc.ipynb (unless otherwise specified).

__all__ = ['load_adult']

# Cell
from fastai.tabular.all import *


def load_adult():
    """
    Download a sample of Adult dataset locally, and load it
    """
    path = untar_data(URLs.ADULT_SAMPLE)
    return pd.read_csv(path/'adult.csv')
