# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/test_nbdev_define_in_subfolder/01 define in multiple_nbs 1.ipynb (unless otherwise specified).

__all__ = ['defined_in_multiple_nbs', 'defined_in_multiple_nbs']

# Cell

def defined_in_multiple_nbs():
    print("This function was defined on notebook 01")

# Cell

def defined_in_multiple_nbs():
    print("This function was defined on notebook 02")